# Generated by Django 3.2 on 2021-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicitem',
            options={'ordering': ['-decrease', '-out_of_stock', '-in_stock', '-increase']},
        ),


    ]
