# Generated by Django 3.2 on 2021-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210603_1440'),
    ]

    operations = [

    ]
