# Generated by Django 3.2 on 2021-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_link_last_run'),
    ]

    operations = [

    ]
