# Generated by Django 3.2 on 2021-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20210603_1442'),
    ]

    operations = [
    ]
