# Generated by Django 3.2 on 2021-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20210605_1745'),
    ]

    operations = [

    ]
