# Generated by Django 3.2 on 2021-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20210605_1812'),
    ]

    operations = [

    ]
