# Generated by Django 3.2 on 2022-02-07 09:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20210716_1037'),
    ]

    operations = [


    ]
